name: Build Azure architecture diagrams

on:
  push:
    paths:
      - "scripts/diagrams/**"
      - ".github/workflows/generate-diagrams.yml"
  pull_request:
    paths:
      - "scripts/diagrams/**"
      - ".github/workflows/generate-diagrams.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies (Graphviz)
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install diagrams

      - name: Generate diagrams
        run: python scripts/diagrams/generate_all.py

      - name: Upload diagrams as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: diagrams
          path: docs/diagrams/*.png